title: Lorenzini
description: "Software-Inspired Discipline for Capital — Investment Architecture Engineered for Discipline."
baseurl: "/SIDC"
url: "https://abraxasq.github.io"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - README.md
